### ISSUE TITLE
谢谢，好用~~~~~~~

### ISSUE THREAD

**Issue by lenmao** [CCBP/TangdouDownloader#1]
谢谢，好用~~~~~~~

**Comment by CCBP** [comment]
很高兴能对你有帮助，如果在使用中有什么问题或建议欢迎与我交流。

**Comment by lyingapril** [comment]
> 很高兴能对你有帮助，如果在使用中有什么问题或建议欢迎与我交流。
v3.0 怎么用啊？
> 在[发布页面](https://github.com/CCBP/TangdouDownloader/releases/)下载打包编译好的可执行程序后便可直接双击运行
