### ISSUE TITLE
源代码运行程序报错

### ISSUE THREAD

**Issue by pkp-pkp** [CCBP/TangdouDownloader#6]
![image](https://github.com/CCBP/TangdouDownloader/assets/105142234/1c4b3c09-02d6-4079-95a6-ada58e031de4)
程序报错

**Comment by CCBP** [comment]
请尝试使用纯英文路径

**Comment by pkp-pkp** [comment]
![image](https://github.com/CCBP/TangdouDownloader/assets/105142234/8976b5a1-d260-49b6-ac98-a0d8a8e02b4b)

**Comment by pkp-pkp** [comment]
> 请尝试使用纯英文路径

我使用的就是纯英文路径  python是3.8

**Comment by pkp-pkp** [comment]
> 请尝试使用纯英文路径
然后那个多余的输出信息是我输出了 video_info的内容，并不存在 path属性值
![image](https://github.com/CCBP/TangdouDownloader/assets/105142234/e9a0c556-fd81-4a18-a9b8-1addf345b422)

**Comment by CCBP** [comment]
BUG已于[dc21c59](https://github.com/CCBP/TangdouDownloader/commit/dc21c59ddc427badce461931abcf682dca754e8e)修复，请拉取最新代码或下载[最新Release](https://github.com/CCBP/TangdouDownloader/releases/tag/v4.2)进行尝试。
